export const templates = [
  {
    key: "employee_registration",
    name: "Employee Registration",
    description: "Collect name, email, and department for a new hire.",
    formName: "Employee Registration",
    formDescription: "Please provide your details to complete registration.",
    createdBy: "",
    version: "1.0",
    sections: [],
    fields: [
      {
        id: "field_1",
        type: "text",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
        minLength: 3,
        maxLength: 50,
        defaultValue: "",
        helpText: "",
      },
      {
        id: "field_2",
        type: "email",
        label: "Email",
        placeholder: "name@company.com",
        required: true,
        defaultValue: "",
        helpText: "",
      },
      {
        id: "field_3",
        type: "select",
        label: "Department",
        placeholder: "Select department",
        required: true,
        defaultValue: "",
        helpText: "",
        options: ["Engineering", "Design", "HR", "Finance"],
      },
    ],
  },
  {
    key: "leave_request",
    name: "Leave Request",
    description: "A two-step leave request with type, dates, and reason.",
    formName: "Leave Request",
    formDescription: "Submit a leave request for manager approval.",
    createdBy: "",
    version: "1.0",
    sections: [
      { id: "section_1", name: "Leave Details", fields: [] },
      { id: "section_2", name: "Reason", fields: [] },
    ],
    fields: [
      {
        id: "field_1",
        type: "select",
        label: "Leave Type",
        placeholder: "Select leave type",
        required: true,
        defaultValue: "",
        helpText: "",
        sectionId: "section_1",
        options: ["Sick Leave", "Casual Leave", "Earned Leave"],
      },
      {
        id: "field_2",
        type: "date",
        label: "Start Date",
        placeholder: "",
        required: true,
        defaultValue: "",
        helpText: "",
        sectionId: "section_1",
      },
      {
        id: "field_3",
        type: "date",
        label: "End Date",
        placeholder: "",
        required: true,
        defaultValue: "",
        helpText: "",
        sectionId: "section_1",
      },
      {
        id: "field_4",
        type: "textarea",
        label: "Reason",
        placeholder: "Briefly explain your reason for leave",
        required: true,
        minLength: 10,
        defaultValue: "",
        helpText: "",
        sectionId: "section_2",
      },
    ],
  },
  {
    key: "customer_feedback",
    name: "Customer Feedback",
    description: "A short rating and comments survey.",
    formName: "Customer Feedback",
    formDescription: "We'd love to hear what you think.",
    createdBy: "",
    version: "1.0",
    sections: [],
    fields: [
      {
        id: "field_1",
        type: "select",
        label: "Rating",
        placeholder: "Select a rating",
        required: true,
        defaultValue: "",
        helpText: "",
        options: ["1", "2", "3", "4", "5"],
      },
      {
        id: "field_2",
        type: "textarea",
        label: "Comments",
        placeholder: "Tell us more",
        required: false,
        defaultValue: "",
        helpText: "",
      },
    ],
  },
];
